#!/bin/sh
# Fetches the cores Diatom is verified against, from libretro's own buildbot,
# and records exactly what was fetched.
#
#   tools/fetch-cores.sh                 the whole test matrix
#   tools/fetch-cores.sh gambatte mgba   just these
#
# Why this exists, and why it records rather than vendors:
#
# Cores are THIRD-PARTY binaries that Diatom does not ship, build or depend on
# (see docs/working-agreement.md). Diatom has no core list. But the test matrix
# is evidence - the geometry, envelope and pacing claims in docs/ rest on
# specific binaries - and evidence whose provenance is unstated cannot be
# re-checked. So the bytes stay out of the repository and the manifest goes in,
# the same trade ADR-0012 made for the sysroot.
#
# The buildbot publishes to latest/, which is UNPINNED. That is the exact drift
# ADR-0012 rejected `:latest` for, and it cannot be fixed from this end: the
# buildbot keeps no archive to pin to. What can be fixed is knowing what was
# actually used, which is what CORES.md is for. A core's own reported version
# string, logged whenever Diatom runs it, usually carries an upstream git hash
# and is the stronger record of the two.
set -eu

ARCH=${ARCH:-linux/aarch64}
BASE="https://buildbot.libretro.com/nightly/$ARCH/latest"
OUT=${OUT:-cores}
MANIFEST=CORES.md

DEFAULT="fceumm snes9x gambatte mgba picodrive genesis_plus_gx mednafen_pce_fast"
CORES=${*:-$DEFAULT}

command -v curl   >/dev/null || { echo "fetch-cores: need curl" >&2; exit 1; }
command -v unzip  >/dev/null || { echo "fetch-cores: need unzip" >&2; exit 1; }
command -v shasum >/dev/null || { echo "fetch-cores: need shasum" >&2; exit 1; }

mkdir -p "$OUT"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

{
	echo "# Cores the test matrix was verified against"
	echo
	echo "Generated by \`tools/fetch-cores.sh\` on $(date +%Y-%m-%d)."
	echo
	echo "**Not part of Diatom.** These are third-party binaries; Diatom neither"
	echo "ships nor depends on them, and loads whatever core it is handed. This file"
	echo "exists so the measurements in \`docs/\` name the exact bytes that produced"
	echo "them. The binaries themselves are gitignored."
	echo
	echo "Source: \`$BASE\` - libretro's own buildbot. The path is **unpinned**;"
	echo "these hashes are the pin."
	echo
	echo "| Core | Bytes | sha256 |"
	echo "|---|---|---|"
} > "$MANIFEST"

for c in $CORES; do
	z="$tmp/$c.zip"
	printf 'fetching %-22s ' "$c"
	if ! curl -sSfL --max-time 120 -o "$z" "$BASE/${c}_libretro.so.zip"; then
		echo "FAILED"
		continue
	fi
	unzip -oq "$z" -d "$OUT"
	so="$OUT/${c}_libretro.so"
	sum=$(shasum -a 256 "$so" | cut -d' ' -f1)
	sz=$(wc -c < "$so" | tr -d ' ')
	echo "ok  $sz bytes"
	printf '| `%s` | %s | `%s` |\n' "$c" "$sz" "$sum" >> "$MANIFEST"
done

{
	echo
	echo "Each core also reports its own name and version, which Diatom logs at"
	echo "load and which usually carries an upstream git hash. Those strings are"
	echo "recorded alongside the measurements that used them."
	echo
	echo "## C++ cores do not run on the Brick as fetched"
	echo
	echo "Measured 2026-08-24: \`snes9x\` and \`gambatte\` fail to \`dlopen\` with"
	echo "\`GLIBCXX_3.4.29 not found\`. The buildbot builds C++ cores against GCC 11;"
	echo "the Brick ships \`libstdc++.so.6.0.28\`, which tops out at \`GLIBCXX_3.4.28\`."
	echo "One version short."
	echo
	echo "Checking \`GLIBC_\` alone does not catch this - the C++ runtime versions"
	echo "its symbols separately as \`GLIBCXX_\`, and a core can be clean on one and"
	echo "fail on the other."
	echo
	echo "The fix is already to hand: the toolchain container from ADR-0012 has"
	echo "GCC 10.2.1, whose cross \`libstdc++.so.6.0.28\` provides exactly"
	echo "\`GLIBCXX_3.4.28\` - the same version the device ships. A C++ core built"
	echo "there runs unmodified, with provenance pinned to an upstream commit"
	echo "rather than to a nightly. Bundling a newer \`libstdc++\` beside the cores"
	echo "would also work and is what other firmwares do."
	echo
	echo "C cores - fceumm, picodrive, genesis_plus_gx, mgba, mednafen_pce_fast -"
	echo "are unaffected and load as fetched."
} >> "$MANIFEST"

echo
cat "$MANIFEST"
